version: "3.7"

services:
  django_web_yassaman:
    build: .
    command: >
      ash -c "python manage.py migrate &&  gunicorn shop.wsgi:application --bind 0.0.0.0:1126"
    volumes:
      - static:/app/static
      - media:/app/media
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dejavu
      - POSTGRES_PASSWORD=dejavu
      - POSTGRES_DB=onlineshop
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
      - ./nginx/config/:/etc/nginx/conf.d/
    ports:
      - 1126:80
    depends_on:
      - django_web_yassaman
  redis:
    image: redis:alpine
    volumes:
      - redis_val:/data
  celery:

    restart: always
    build:
      context: .
#      dockerfile: dokckerfile-name-alternative
#      args:
#        name : ashkan
    command: >
      ash -c "touch celery.log &&  celery -A shop worker -l info &> celery.log"
    volumes:
      - .:/app
    depends_on:
      - django_web_yassaman
      - redis
volumes:
  postgres_data:
  static:
  media:
  redis_val:
