# Generated by Django 3.2.7 on 2021-10-13 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carts',
            new_name='Cart',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
