# Generated by Django 3.2.7 on 2021-10-10 14:24

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=utils.upload_image_path),
        ),
    ]
