# Generated by Django 3.2.7 on 2021-10-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211008_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='invertory',
            new_name='inventory',
        ),
    ]
