# Generated by Django 3.2.7 on 2021-10-13 12:01

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_gallery_image_path),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
